apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        name: kiali
        kind: HelmRepository
        namespace: flux-system
  values:
    server:
      web_fqdn: kiali.internal.${SECRET_DOMAIN}
    auth:
      strategy: anonymous
    deployment:
      ingress:
        enabled: true
        class_name: internal
        override_yaml:
          metadata:
            name: kiali
            namespace: istio-system
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            rules:
              - host: kiali.internal.${SECRET_DOMAIN}
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kiali
                          port:
                            number: 20001
