---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age18mjkm8tfkt8cchsh6pyn0cmue89qy5ks3t689uuueuwfj0pk640q9p8teg"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age18mjkm8tfkt8cchsh6pyn0cmue89qy5ks3t689uuueuwfj0pk640q9p8teg"
