---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  chart:
    spec:
      chart: sonarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    env:
      TZ: America/Chicago
      PUID: 568
      PGID: 568
    image:
      repository: linuxserver/sonarr
      tag: develop-version-4.0.0.752
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &host sonarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls
    persistence:
      config:
        enabled: true
        storageClass: nfs-client-ssd
      vids:
        enabled: true
        mountPath: /data
        storageClass: nfs-client-ssd
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        size: 250Gi
