apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:X1ZvTS1UXSX6ueBp8lEGfDYqBedIUqXj5/NV+1ecdeo3ADXQ,iv:vlLmumoiJ+X/h8+hU3kgHhKcfsFoxnFFBmgGJBfJWPs=,tag:fyxxAqvHiSTTtRLtTjnSlQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:aeGv+JnBKG2POFNjaviIRdSHdHgCfN8hJk9Z8W10s0k1XxcFb6LX7eMv6At8RTEvOQwN2geVmIX2uXIMPnZUS+YZ7j5cDqdaZE7GCuOS1YWWY61Rc84JXqblOH8knYgtOMU0kaeI0x6Kt1sqI1lHPVcwjgqO5dhnb8uriBvMdA+lQDGnejs+V9FT2C4yKmGVm0/52VX3KpQ7lLOsEnPMVI7ztoWTBzKgUQ3R61utjg==,iv:lNI20+pHXzweWYQPwgYunu8j/JRTkgIxDlHJ6BD8d58=,tag:kY6SEs5q8lmswUPHm7BofA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcvzhphtuxus8lqt6976570rvf000crvuktjuruzkptgqp2wscmqeycqjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZTd3bGJ6N3FwdzlKMUJW
            QXV1TE1BeVBZTXFKT1htK1FNSnZZa21MWlFBClZmOGRjeGZlaWIwMW5WdC9nVnQ2
            ZmhpRXBXMU9IbTR2d2JtRkYxcjhsT0kKLS0tIG4rSEU5N21hclJSTmNtNjRJNW9y
            SG9oMGllbmVMNkRCK0VaemFXUForbmcKI2LWBHnMhsFBSlgj1WA1Wrx9ZzU7tK2o
            O6/YIi9QBRU17erFqmnXID3HEm0R0p3BJPGnxppIblTGh99pJNHLVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T16:36:13Z"
    mac: ENC[AES256_GCM,data:BHB2VOHX6hynndugLfgmH7RbjAr2SGepZ+4KVpZYfdStNJWMLb2mNADlStwadm9afPMCYLBquurFJDQLTM2MB4NMUaSHEXU2ciCZZiQf0Exg6JUZsAIDQNDfpLqlnqNpj2INTA3jWoMjCbJuKxs+/jzegc39NMT2glXr1vXJ3Ig=,iv:nfjAAI36rbds6HhTIM7SfhxQjU8Tz1J0Zi5TXI4kYZI=,tag:qWq20TDNlZR1drnEcJedYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
