apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:66Ru8wEOAeiVtuQvTjUICJE3+q60tRuahUVuxlLZ+qlqb6XH,iv:bOoFS7BI3haZjCIG3Ely/Bc4QeqINjJeqBx7/VoHQ5c=,tag:t1zsLfHcyBIiOl1GfHoEWA==,type:str]
    credentials.json: ENC[AES256_GCM,data:JfFIMFs3utUIkqBTAAbtdS+e6Nvbz3Cjk2ugB3GNuXsvybqi7K2Ch+2y57qfjDQ7bs5NAO1E1K7E/natE/ONkM0p/hkZBQe7oF7MgFHfdHNJHBk/A7BxGYbZmU19ZiU7QfRfnsYUOZCg7pGV6eyPLfC/r7aifDZDPrIRkJWYReh7sEGxf0LMO9esq1kg//4xROrYuUquyaJZoPO9IvZXlYPDK+RfAgaTpTur5cMvlQ==,iv:UwpM+JoWebply6lp6v5zWlk0cZOwhVQbeTt/Y2z61qI=,tag:5o8GXRL8e9Tx50f/lvUV1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ygul6zx4p6r3we78rupvtkdac3t4mxwzzfv5qr4mlfmz2gqmcaqh8fer6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRE9scjRsTSsxTzhwSkg4
            U0l3Y2x5QjNiZGx1Tm83ai9IZStHZnRxdGhFCjJWM1FZb2FuTmNIMVB4eGMrTkZQ
            Q3BxeDU0L1FKTDV5STJyeG1XQVJoL0EKLS0tIGZYTFc3dGZYaGxFQjh4Z1JJQklE
            U2g5RjNvSWhXU21zU29QQ1huaGpDOXcKIlclifjd82rzDEvDdqz8W3Jqiabzeh8m
            oVls9Zpxdh0BvIrt6y1vGcY8vzgQtUdFmSO/MvfYBmL1CzvTmavLtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T07:17:00Z"
    mac: ENC[AES256_GCM,data:aPiHA7Tnztby+lvqBocQw3GCvnwEXJT2z5UXj1YgPdzj2MCNDqyyiyw9/m2P2r10Euvn3eXixltnY90OlF1Iln/+Ilz3YeR3t83zXOPr6bosoDG2b0C8zEfRmAJH27KQDHlwvYsLldIrOFXJNIcIOpWA+fXGe1wGiIhyt3w0v8E=,iv:B2tL9LshCg1o3AnvOuGYjy/Txa7UYCKAmsW+hEHL4gE=,tag:D7XKxOWPyA0gPglhI6cwpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
