---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tubearchivist
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 1h0m0s
  releaseName: tubearchivist
  targetNamespace: default
  maxHistory: 2
  values:
    global:
      fullnameOverride: tubearchivist
    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: bbilly1/tubearchivist
              tag: v0.4.10
            env:
              - name: TZ
                value: America/Chicago
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TA_HOST
                value: tubearchivist.internal.${SECRET_DOMAIN}
              - name: REDIS_HOST
                value: redis
              - name: ES_URL
                value: http://elasticsearch:9200
            envFrom:
              - secret: ta-creds
          es:
            image:
              repository: bbilly1/tubearchivist-es
              tag: latest
            env:
              - name: ES_JAVA_OPTS
                value: -Xms512m -Xmx512m
              - name: "discovery.type"
                value: single-node
              - name: "path.repo"
                value: /usr/share/elasticsearch/data/snapshot
              - name: "xpack.security.enabled"
                value: "true"
            envFrom:
              - secret: ta-creds
          redis:
            image:
              repository: redis/redis-stack-server
              tag: latest
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            primary: true
            port: 8000
          es:
            enabled: true
            primary: true
            port: 9200
          redis:
            enabled: true
            primary: true
            port: 6379
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - host: tubearchivist.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: tubearchivist-tls
            hosts:
              - tubearchivist.internal.${SECRET_DOMAIN}
    # serviceMonitor:
    #   main:
    #     enabled: true
    #     serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: nfs-client-ssd
        size: 10Gi
      youtube:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media-pvc-ssd
      es:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: nfs-client-ssd
        size: 10Gi
        advancedMounts:
          main:
            es:
              - path: "/usr/share/elasticsearch/data"
                readOnly: false
      redis:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: nfs-client-ssd
        size: 1Gi
        advancedMounts:
          main:
            redis:
              - path: "/data"
                readOnly: false
