---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.3.2
  interval: 1h0m0s
  releaseName: qbittorrent
  targetNamespace: default
  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 4.6.4@sha256:d7620ef51467015e1cffab143d053a7dfbc2d7a6f50b3491427df7cd40cf16a9
            securityContext:
              runAsUser: 568
              runAsGroup: 568

          gluetun:
            dependsOn: main
            image:
              repository: qmcgaw/gluetun
              tag: v3.38.0
            # See [image docs](https://github.com/qdm12/gluetun-wiki) for more details on how to configure
            # your VPN and how to set up port-forwarding.
            env:
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: mullvad
              # DNS_KEEP_NAMESERVER: "on"
              WIREGUARD_PRIVATE_KEY:
                secretKeyRef:
                  name: qbittorrent-wireguard-private-key
                  key: wireguardPrivateKey
              SERVER_CITIES: "Ashburn VA"
              WIREGUARD_ADDRESSES: 10.71.1.130/32
              # WIREGUARD_ALLOWED_IPS: 0.0.0.0/0
              FIREWALL_VPN_INPUT_PORTS: "8080"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          # port-forward:
          #   dependsOn: gluetun
          #   image:
          #     repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
          #     tag: "1.3"
          #   env:
          #     - name: QBITTORRENT_SERVER
          #       value: localhost
          #     - name: QBITTORRENT_PORT
          #       value: "8080"
          #     - name: PORT_FORWARDED
          #       value: "/tmp/gluetun/forwarded_port"
          #     - name: HTTP_S
          #       value: http

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: internal
        hosts:
          - host: &host qbittorrent.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      # Configure the main configuration storage location
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          main:
            main:
              - path: /config
    gluetun-data:
      type: emptyDir
      advancedMounts:
        main:
          gluetun:
            - path: /tmp/gluetun
          # port-forward:
          #   - path: /tmp/gluetun
          #     readOnly: true
