apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wireguard-private-key
    namespace: default
type: Opaque
data:
    wireguardPrivateKey: ENC[AES256_GCM,data:UcpxOw3rFoaiQGXPjJXjfbWNg8KCBjw8/mymNqGtuDWsRpcvjBSybafwkRPtJxM/WkmfGzsps1dn1sL3,iv:9sg2HhWN7k1qGjoXiG+VD2/sgrdP2tFd5bR1TYVMHHs=,tag:h6kgdcuIMovjr+BxYh0EEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r44tzdpkykthpxm8327sx2fgnt4lgu7y5wglun2cxxllrmau9g8qapyq8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NG9Mb3BzbytrMUEwSzZq
            dWNFUmg1ZVJXbndsZ3FmcVhneGRGVFRoakV3ClNiRk5UZGxULzBMMHFzWElYbHZw
            YWVuZDN3VFAvbWo5Q0FpUXRDUnRUWmcKLS0tIENSRFBCNExrYWZiczN3V2JLZXdt
            ZVp1aWhGdndSZ25VREtaZ0hpeG9IVXcK0u1T8igoHKhqr2GV8HZoU5KGAW1Faln8
            KzmVq4Km22l5T/ty3orW2QxaRqD3Yfw/CUmxPscmoOt2az/Ym6JEzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T01:08:21Z"
    mac: ENC[AES256_GCM,data:Wd9uouk/qt1BKAoitv6OO8hS6DQZ5T9I4hWXIvWBTB1uHFIuM5AZ8d4YGFyQgusaWRQEDmRDeDEJ/gh/Bp7CUt9v5We+YMU7nUQp3SGaxjfc6z3zhFrs9e3gjVEm6Pb6XIe4a/H0mE/Jx/pSArKc8HeTvUbsjSzeE5q4kJaRv7U=,iv:jkXM52BCr39j4LAPW4BIkF69rPxhz3Oz5qKkx9VSk4o=,tag:FbS5Q4ZlxHXZ1osGryT1mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
