apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:xJgsEnm1ew+xXaSDRarLN305kW0j/Fm6Glx+S3aQxlDWVHUAKK1PFg==,iv:O/QNzcPsVfP3Z7bxIJwwywTgnqW0KDo07rNm85u0zNw=,tag:xbs4/pgF9/gkZgw/RiZG1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r44tzdpkykthpxm8327sx2fgnt4lgu7y5wglun2cxxllrmau9g8qapyq8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUnk4eVJiVFFSOEk1UGFM
            TDEycXRuV3lrRW1YUUZCaHlpQlI2TEpWNERNCk5FZUxFMWRSWFFJQUh0bWRhN2l1
            bmlmanpwejlKQXIrblpaMlpVU3NiU1kKLS0tIDR4MVpCaVhBUVhqeDFOQ2JyZENJ
            d2xVMmxGdkRqTTJBcy9tVjVJemtMNDAKEDKIshs5JAdG77doLF5UBRiSGYCHpDGX
            yMPVDhWIdTwRMo8IgRBHzG32xEe8kuSQMt+9vlNk+SQhpqENtNbWkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-17T00:02:19Z"
    mac: ENC[AES256_GCM,data:l8YQ9MWrr/e/yjUDGWB41sqKM5zruHmxmD24m4/niix/+U2OxGu7VOQLkOmXnRZENx4WJi3znCK7opixw8tH2ofy3PcYaudLwc+IHLP1IRjf79m85EhzWL+2UCCtr/CGvLtY/RfWWSxRO2gbDHqI9TzRH5q+wtx1CiMmBcUQ5Xg=,iv:rX+Ws1jItWQkIbZXtIycMO4/Xtbg4VIiJWAIPR1qMM8=,tag:9WTx0PMlXK4YpbpWsUuP1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
