apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:yXxqg7JGBaRSVyxBeKjwDWFnICcM8ww3yplmlj7yQ/aEwzyU7IvrnIC16t1HI1VDByIxblpWVz5vCLCmPAKv+dZW1enEhmxbcGLXI2hw8Q2M1v3yJAI2UDWjTDelIQ==,iv:F61+SYlb9tBWelltlcdq0dhStTrsXqWtdG+SFnnoYWQ=,tag:kQwQM5E9Cky/dNsNT4iYbA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1n29JF67YY4caIA=,iv:VgPiiFbdbzVZwypCnaVOqavNvvxrPLIpT3m8sYcaVKc=,tag:KQ+6d/nhci58mPuIS9csqg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QL/DKu4XkNbHxVIp1ZTeu+X56sJNTg==,iv:G+wx3Zek3W+l37AQ2NY6cYK3ur503se14RvCSQ5MHQM=,tag:EGGQGoIFP/0EMh6NGvtDMA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lB2ZSdXi3oDsnDjz4Rx8LBRvu7/ONGsHL01LGVVXEzW5opGa,iv:k6jO8qJJNlSDsB410Id9sqfxn8HSImic+OxBjLSPVgA=,tag:SXnr+QuiWl0Gm1Mf6DQDXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15ygul6zx4p6r3we78rupvtkdac3t4mxwzzfv5qr4mlfmz2gqmcaqh8fer6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMFVPQ0tJUU9aSjJHUW1j
            eCtYNkJ1VFk0VU1jOHF5Sjk4dG5YMEFvSmlrCmJRajZTTit2aTZmUVVGSzhYQURN
            RThUcEVTcjJsd2VsdkgwZXNWSDMrU1kKLS0tIGdFVUxMc050MURwVHZZNVlWNkZQ
            U3JNYzdoMUdwbFBxeHA5bkJzOUN0Mm8KJg8RheSXMhgoZtoMJ9053lT1A91TxvGu
            E6/AqBDO6yIBjaIs0q/o1eRZTX+n4BG5kSJ7Bc1GNq/5eqq+/y31EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T07:17:00Z"
    mac: ENC[AES256_GCM,data:yo00OTnIPbZ6z2aUIGlai+4bP0ez+RKQpEVB2M9CVYNLpLsnSRbrFYW8O4GpzR4l2vL6BlabXh7zAkH4DVOUcI6LIj/Z+dKEOhxQXb7acvikWOdoSZ9bEOkJ+4kuHjWxBooa+F6U43g9tV/FTtih4aabYVnE4X180SxirJ6YUEg=,iv:GsI7DfpUrGa3ToT1S4ElyHs4XNSAgNy7S6x+Rkqaj4E=,tag:gqegSgOxhU8H8XP1kJKyVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
