apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: default
spec:
  chart:
    spec:
      chart: overseerr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 5.4.2
  interval: 10m0s
  install:
    createNamespace: true
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  values:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    image:
      repository: sctx/overseerr
      tag: 1.33.2
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        storageClass: nfs-client-ssd
        size: 10Gi
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:movie
        hosts:
          - host: &host overseerr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: overseerr-tls
