apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2qE941RLZ7L4FaVwUNDD9WqLniW+DCx4i384KTuFJvA=,iv:95iNe5/H8j9G1+BsRcrs59K9rLdG/aQ1lNoFY5Z90Hs=,tag:wwlwOR2DI1JLybXxmfTm/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL0prWHpWMnRNTDR5eVhS
            UnhOclcwbytRamlCbDBrQnZZeHNKN2pmUjBvCllpZlFZVHdLWWhtUit2S2dDN0FY
            YW1sUW1VMmNpTy9sSWFEMnhwekJzK0UKLS0tICtmcnQ2VzJZQmhoT2RMSHg3NnNK
            NWhqb2NyWkZhS2QwbE9PcUtha1MzK3cKR36+Y+j0eHKiRHzRVkEWBLdOLwt4PO9O
            OuAEgH5+xnRNaso4WfUm+n56zQ+vYkOMYVu3WFeMFfxKfOKFO/IfkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T16:23:51Z"
    mac: ENC[AES256_GCM,data:DE1QFkvWkBYPeoA/MmZO+zLLbVkRRpzPOm9fsW2ftEeDXR3Ch1mh7+nAkmRvntJdRHTqMVWgohSEj4hUTC9hLEhasl5ZcF4+jUlMIHgGZeZJur7pWbC/suQolVRlyhqJgbP3ZAO0Q3r6MsCgwSkuCoVUFC9R7b8iYe8Pa9M6o+M=,iv:0knWIuC4MTHCMoDrASe+pSTXp5aG+xFwMFcXl7l90tM=,tag:XcrUIBxw2CYpNPbtveo1ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
