apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Uk/iLsXVbVCOkfdGbgjaZ5WxeYn5KF+ON25cJZSFDYM=,iv:Yh7Mm4EVR28C48EjMScJisZgejQphmQZlO5Qt0V5oUY=,tag:coIDpO0mfMevDMWuK+UI+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18mjkm8tfkt8cchsh6pyn0cmue89qy5ks3t689uuueuwfj0pk640q9p8teg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MFBsTG1MSDVFUkZwM3hj
            WFpwd0ZGN2pTeTBOVWVHVUxFQkw4TTg1MVJvCkFmdlcyV0RNNWh5bkdibWU1TzM1
            eGgweStzdUszY2FRdnM0aHd6SEcvRDAKLS0tIDRlbnNJV1VWQ3AySXNTSmF6dXpu
            MFcyUjNZMFVoeDJ6bWFldDY1TDNIcTAKBpGjyggoVJ+1QoFbE4pfiurrS7H3pNJo
            MeNLqEx0j+w1eYamTB/h6VNxHhiAYOgmO1MGTkvYC98aSHARtxcgOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T21:32:02Z"
    mac: ENC[AES256_GCM,data:A1K2jSU2Z7VJ8iDk2qaqNDLz3k0jYr9pEhqngFzASMrnqC8xBm4Dz7HO/RmjJg+617q1ELU1//ogfqndoGEU/e6jBIBRq3Fg8sc8i16G62qj6zlXHVwH7DyN75jyHHMuOEKKLyKZyEd7zuBxttDbMNgWvNKL/V3gCNHhuwZIaGg=,iv:444RsOCQFWFXejszDySfK1Agia5XqGgFxGwcgNgY/vA=,tag:0lKKyP+lutr+f/qxs3El1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
