apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xrODi4xUjHH+E8fdurGWYA9b0lR3hM2YiU2AVQTYu0I=,iv:MffiNf09vDJS0LE+iXCsye+G8VJy9gK08ZM5WLnChec=,tag:KajqiHJREC14kbgH3G6LIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r44tzdpkykthpxm8327sx2fgnt4lgu7y5wglun2cxxllrmau9g8qapyq8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMzdiZ3NlQU40NDdKRUxT
            UVJwbCtleitnRENEaUlkcTFNRyt6ekRtN3hnCk5SNDBnd2tZMEh5ZEh0ZFZESDg5
            ZmIreXltQlpYNGVEOUZOUk9jS0JEMEkKLS0tIERhQk80dGhMb0VVTHF0azBlR3ZH
            RDFHckFFeFZETXE2Q0pXVUxoNTJtRm8KoSCZtE/Hk0AS57AXWxvkAADu96ZAJZwP
            bSkOJTx+R7zV/6fy0S7BpG+fwBt2aK7AsMaubeJrIgEEFR63Aetkrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T01:53:03Z"
    mac: ENC[AES256_GCM,data:Q2Wr9vw/faOpG//Hshs429KsgdEAUBA6beCyE29Hqrs7SkooEHU2+/BnHXPK5WjG70FPa+2ZtOO2cpvXWMJqPaf5f+gSfKz8L5sD0ZIuj1UmiwpWf/KLw57nCqn7Xf1//I4souUP/wQcvwYn2jdm9p3GXryQCm12809PUaA68rc=,iv:HuSFkc6LwoQVj4pUKO+t+SHAEu11l+JwiJwIBQuKtCE=,tag:EazT90NPkKh3tK6+F4i+Eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
