---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
spec:
  chart:
    spec:
      chart: jackett
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 11.7.2
  interval: 15m
  values:
    image:
      repository: linuxserver/jackett
      tag: 0.22.501
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host jackett.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jackett-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: openebs-hostpath
