apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:w3LYRtAb3LGrs+UaX13rf9tg5bUjqNiyQeHUI5abtTgqvnOHXr7/ew==,iv:LIj1mmm+vpV/eCfJs0Xguhx1YgY9hCThZjeVyrV9QV8=,tag:z3m3uZx4ELFYWLqFlUcH5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbzVOQ2dxb0d1ZmR3Qmdx
            cWE2MnFJSkxPZ1BzemYxb2NxQVkySkhJOXpVClluTStGcVpLR3RTUnY1OUQvSlN2
            UXpkSXE2ekRlQ0c0WlZvOC9mbTBudGMKLS0tIGFOSmlGWHNxWnREQmNGMEhNS3Zp
            R3djeFExUFFPRVpPMlNJdG5XbzJldXMKnHwqXybv27M5IE4S7p5qMUh5PKkJcVIe
            H8yyFG5MOPueBY90OwOYlroje5XvVfv8MFlPKkIjgw/VjlYdPKzwDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T16:13:38Z"
    mac: ENC[AES256_GCM,data:eR1ROhE6eB/GLgzZA4erNkBfVEfX6gsw0jVAJA9+6UTr3P93mkS9KFkLlxlDmm7fU58Q9ajEu6tibjlo3dG/4m7qFBazARFnlCwIkChTpiR42LKrq2DvsUVu3tcid2Dwye+lpRixdre3C0BU/p7PpNU4p/MILSZTj8yAADdewbE=,iv:8d1kcSJRarPdGGziFtrbTgj4Qmo9Zj8Pw0v7MQfdzi0=,tag:qJ1GRpjBIfw3zlHPQYljzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
